"""lab3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uSMukaAQ9RwUP2EFVfp_3gmy6anEqjen
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""2.1 Attack Human-Detection

(1) Detect without patch
Utilize the apis in detect.py to recognize images of people. Feel free to edit the source code if it's needed. The result should be plotted after running the code.
"""

# Commented out IPython magic to ensure Python compatibility.
# Your code starts here
# Hint: To directly run the main function in a file, use 
# %run file_name.py param1 param2 ...
import detect
import train_patch
import test_patch

def detect_img(imgfile):
  detect.main("cfg/yolov2.cfg", "weights/yolo.weights", imgfile)

imgfile_wo_patch_person = "persons\person_001.jpg"
detect_img(imgfile_wo_patch_person)

"""(2) Train patches
Now we will train two patches by ourselves. One of the patches has a starter image as input and the other one is completely generated by our code. To do these, please 


*   Take a look at train_patch.py and edit the relevant code.
*   Write a wrapped-up api for generating these two kinds of patches.
*   Call the api to generate a with-starter-image patch and a without-starter-image patch.

Please make sure to save these images since you need to use them in the next step.
"""

def patch_training_caller(trainer, starter_img): 
  
# set train mode to 1 if without starter image or set train mode to 2 with starter image

# Call patch_training_caller to generate a patch with starter image
  train_patch.main(trainer, starter_img, 2)

# Call patch_training_caller to generate a patch without starter image
  train_patch.main(trainer, starter_img, 1)

"""(3) Detect people with patches
Use the same api in detect.py as section 2.1 (1) to detect people who hold the patch picture you generated in 2.1 (2). The model should not recognize the people in this case. 
"""


# Your code starts here

imgfile_w_patch_person = "" # set path here
detect_img(imgfile_w_patch_person)

"""2.2 Attack Stop Signs-Detection

(1) Detect without patch
Similar to 2.1 (1), first we need to use apis in detect.py to recognize images of stop signs.
"""

# Your code starts here

imgfile_wo_patch_stop = "data\stop.jpg"
detect_img(imgfile_wo_patch_stop)

"""(2) Patch stop signs
* Edit the source code involved in the patch-sticking control flow to attach the patch image on all the stop sign images. Images belonging to any other class (i.e. people, horses, etc.) should not be patched.
* Write a wrapped-up api for sticking patches on stop signs.
* Call the api to stick patch on stop sign. You should specify which patch is used in parameter.

"""

def patch_sticking_caller(patchfile, imgdir): # patch file is the patch you want to put on the stop sign and the imgdir is the directory that includes a non-patched stop sign
  # If there's no stop sign in the image, the image should not be patched.
  # Your code starts here

  test_patch.main(patchfile, imgdir)

# Call patch_sticking_caller to stick a patch on stop sign image. 
# Your code starts here

"""(3) Detect stop sign with patch
Use the same api in detect.py as section 2.2 (1) to detect the patched stop sign. The model should not recognize the stop sign in this case. 
"""

# Your code starts here
imgfile_w_patch_stop = "" # set path here
detect_img(imgfile_w_patch_stop)
